version: '3.8'

services:
  backend:
    build:
      context: ./virtualBookshelf
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/virtualbookshelf
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      APP_JWTSECRET: yourSecretKey
      APP_JWTEXPIRATIONMS: 86400000
    depends_on:
      - db

  frontend:
    build:
      context: ./frontendbookshelf
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: virtualbookshelf
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
